# Generated by Django 4.2.16 on 2026-06-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steprun',
            options={'ordering': ['id']},
        ),
    ]
